name: Blogger Trends Hourly Bot

on:
  schedule:
    - cron: '0 * * * *'  # Executa a cada hora
  workflow_dispatch:      # Permite execução manual na interface do GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Recreate config and credentials files
      env:
        ENV_FILE: ${{ secrets.ENV_FILE }}
        CLIENT_SECRET_JSON: ${{ secrets.CLIENT_SECRET_JSON }}
        TOKEN_JSON: ${{ secrets.TOKEN_JSON }}
      run: |
        echo "$ENV_FILE" > .env
        echo "$CLIENT_SECRET_JSON" > client_secret.json
        echo "$TOKEN_JSON" > token.json

    - name: Run Blogger Bot
      run: python blogger_bot.py
